"""initial schema

Revision ID: 11e7da409011
Revises: 
Create Date: 2026-09-23 17:00:25.506680
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '11e7da409011'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nid', sa.String(length=17), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('spouse_name', sa.String(length=200), nullable=True),
    sa.Column('father_or_husband_pref', sa.String(length=10), server_default='father', nullable=False),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.String(length=12), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('present_address', sa.String(length=500), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nid')
    )
    op.create_index(op.f('ix_people_phone'), 'people', ['phone'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number_norm', sa.String(length=50), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('chassis_number', sa.String(length=50), nullable=True),
    sa.Column('engine_number', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
    sa.Column('previous_registration_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number_norm')
    )
    op.create_index(op.f('ix_vehicles_chassis_number'), 'vehicles', ['chassis_number'], unique=False)
    op.create_table('ownership_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('registration_authority', sa.String(length=200), nullable=True),
    sa.Column('sale_price', sa.BigInteger(), nullable=True),
    sa.Column('sale_price_words', sa.String(length=300), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('fee_bank_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('registration_number_norm', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('chassis_number', sa.String(length=50), nullable=True),
    sa.Column('engine_number', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
    sa.Column('previous_registration_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_transfers_chassis_number'), 'ownership_transfers', ['chassis_number'], unique=False)
    op.create_index(op.f('ix_ownership_transfers_registration_number_norm'), 'ownership_transfers', ['registration_number_norm'], unique=False)
    op.create_table('transfer_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('spouse_name', sa.String(length=200), nullable=True),
    sa.Column('father_or_husband_pref', sa.String(length=10), server_default='father', nullable=False),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('nid', sa.String(length=17), nullable=True),
    sa.Column('tin', sa.String(length=12), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('present_address', sa.String(length=500), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['ownership_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'role', 'position')
    )
    op.create_index(op.f('ix_transfer_parties_nid'), 'transfer_parties', ['nid'], unique=False)
    op.create_index(op.f('ix_transfer_parties_phone'), 'transfer_parties', ['phone'], unique=False)
    op.create_index(op.f('ix_transfer_parties_transfer_id'), 'transfer_parties', ['transfer_id'], unique=False)
    op.create_table('witnesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['transfer_id'], ['ownership_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_witnesses_transfer_id'), 'witnesses', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_witnesses_transfer_id'), table_name='witnesses')
    op.drop_table('witnesses')
    op.drop_index(op.f('ix_transfer_parties_transfer_id'), table_name='transfer_parties')
    op.drop_index(op.f('ix_transfer_parties_phone'), table_name='transfer_parties')
    op.drop_index(op.f('ix_transfer_parties_nid'), table_name='transfer_parties')
    op.drop_table('transfer_parties')
    op.drop_index(op.f('ix_ownership_transfers_registration_number_norm'), table_name='ownership_transfers')
    op.drop_index(op.f('ix_ownership_transfers_chassis_number'), table_name='ownership_transfers')
    op.drop_table('ownership_transfers')
    op.drop_index(op.f('ix_vehicles_chassis_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_people_phone'), table_name='people')
    op.drop_table('people')
    op.drop_table('users')
    # ### end Alembic commands ###
